In [1]:
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


In [1]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

env.close()

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[-0.01008172  0.02685631  0.02499156  0.0056852 ]
[-0.0095446  -0.16861497  0.02510526  0.30614732]
[-0.0129169   0.0261404   0.03122821  0.02148649]
[-0.01239409  0.22080091  0.03165794 -0.26118232]
[-0.00797807  0.02524169  0.02643429  0.04131542]
[-0.00747324  0.2199748   0.0272606  -0.24291142]
[-0.00307374  0.41469697  0.02240237 -0.52687253]
[ 0.0052202   0.60949666  0.01186492 -0.812413  ]
[ 0.01741013  0.8044541  -0.00438334 -1.10134037]
[ 0.03349921  0.99963345 -0.02641015 -1.39539529]
[ 0.05349188  1.19507385 -0.05431805 -1.69621734]
[ 0.07739336  1.39077867 -0.0882424  -2.00530326]
[ 0.10520893  1.19668024 -0.12834847 -1.74119804]
[ 0.12914254  1.00323216 -0.16317243 -1.49104362]
[ 0.14920718  1.19992077 -0.1929933  -1.82991768]
Episode finished after 15 timesteps
[ 0.03494981 -0.00303134  0.03338247  0.01061278]
[ 0.03488918 -0.19861574  0.03359473  0.31363855]
[ 0.03091686 -0

[ 0.0707524   0.39145835  0.00476999 -0.46010057]
[ 0.07858157  0.1962693  -0.00443202 -0.16591796]
[ 0.08250696  0.00121107 -0.00775038  0.1253635 ]
[ 0.08253118  0.19644319 -0.00524311 -0.16975447]
[ 0.08646004  0.00139668 -0.0086382   0.12126981]
[ 0.08648797  0.19664132 -0.0062128  -0.17412582]
[ 0.0904208   0.00160883 -0.00969532  0.11659071]
[ 0.09045298  0.19686835 -0.0073635  -0.17913518]
[ 0.09439034  0.00185254 -0.01094621  0.11121576]
[ 0.0944274   0.19712962 -0.00872189 -0.18490043]
[ 0.09836999  0.00213354 -0.0124199   0.10501836]
[ 0.09841266  0.19743126 -0.01031953 -0.19155698]
[ 0.10236128  0.00245844 -0.01415067  0.09785278]
[ 0.10241045 -0.19245787 -0.01219362  0.38603782]
[ 0.0985613  -0.38740462 -0.00447286  0.67485137]
[ 0.0908132  -0.19222079  0.00902417  0.38076354]
[ 0.08696879 -0.38746972  0.01663944  0.67627807]
[ 0.07921939 -0.19258288  0.030165    0.38888005]
[ 0.07536774 -0.38811971  0.0379426   0.69091904]
[ 0.06760534 -0.19354421  0.05176098  0.4104183 ]


[-0.0717234  -0.16105465  0.03331681  0.30651255]
[-0.07494449  0.0335771   0.03944706  0.02452029]
[-0.07427295  0.22811179  0.03993747 -0.25546032]
[-0.06971072  0.42264144  0.03482826 -0.53528363]
[-0.06125789  0.61725677  0.02412259 -0.81679215]
[-0.04891275  0.81204031  0.00778675 -1.1017911 ]
[-0.03267195  1.00705895 -0.01424907 -1.39202091]
[-0.01253077  1.20235539 -0.04208949 -1.68912492]
[ 0.01151634  1.00774444 -0.07587199 -1.40983768]
[ 0.03167123  0.81364105 -0.10406874 -1.14180519]
[ 0.04794405  0.6200216  -0.12690485 -0.88348832]
[ 0.06034448  0.42683023 -0.14457461 -0.63324158]
[ 0.06888109  0.62364154 -0.15723945 -0.96773566]
[ 0.08135392  0.82048529 -0.17659416 -1.30539683]
[ 0.09776362  0.62798628 -0.2027021  -1.07278826]
Episode finished after 24 timesteps
[0.00027868 0.03682398 0.04986194 0.00849554]
[ 0.00101516 -0.15897628  0.05003185  0.31648425]
[-0.00216437 -0.35477385  0.05636153  0.62451631]
[-0.00925984 -0.16048217  0.06885186  0.35010308]
[-0.01246949 -0.35