In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('FrozenLake-v0')

In [26]:
T = np.zeros([2,3,4])
T[1,:]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)
    

In [5]:
print("Score over time: " +  str(sum(rList)/num_episodes))


Score over time: 0.454


In [6]:
print("Final Q-Table Values")
print(Q)


Final Q-Table Values
[[4.76669630e-02 7.67250367e-03 1.09732081e-02 1.10060170e-03]
 [8.56300571e-04 0.00000000e+00 2.87852542e-04 1.12220830e-01]
 [1.56128700e-01 5.42299455e-03 5.25707131e-03 5.20002759e-03]
 [4.41805737e-03 2.79173909e-05 0.00000000e+00 5.18834161e-03]
 [9.36823013e-02 1.32983680e-03 5.79036247e-05 5.54472234e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.56551252e-04 7.94262297e-08 1.34409795e-01 1.31764802e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [5.64848819e-03 5.39413709e-04 1.20801541e-04 1.12017841e-01]
 [0.00000000e+00 6.14569893e-01 3.32220688e-03 1.12538888e-04]
 [5.27290535e-01 3.56396050e-04 8.02025420e-04 3.31875671e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.29724064e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.00633863e-01]
 [0.00000000e+00 0.00000000e+00 0.